apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dummy-gihub-comp
  annotation:
    backstage.io/techdocs-ref: http://mydoc.location.com
  description: A dummy public component in github, wait for auto update of description
spec:
  type: website
  lifecycle: development
  owner: team-b
